spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5433/01blog_db
    # url: jdbc:postgresql://postgres:5432/01blog_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ddevtools:
    restart:
      enabled: true
      poll-interval: 1000
      quiet-period: 400
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  # config:
  #   activate:
  #     on-profile: dev
      
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 8640000000
app:
  cloudinary:
    cloud-url: cloudinary://642694169257984:rfJHdHX8xcB3gLsKDpYFDI6qLv4@dbwhdxois

resilience4j.ratelimiter:
  instances:
    myApiLimiter:
      limitForPeriod: 40                    # Number of requests allowed in the period
      limitRefreshPeriod: 1s                # The time period
      timeoutDuration: 0                    # How long to wait for permission (0 = fail fast)

  

  