spring:
  application:
    name: backend
  datasource:
    url: ${DATABASE_URL}
    # url: jdbc:postgresql://postgres:5432/01blog_db
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_USERNAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ddevtools:
    restart:
      enabled: true
      poll-interval: 1000
      quiet-period: 400
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
  # config:
  #   activate:
  #     on-profile: dev
      
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY} 
    expiration-time: 8640000000
app:
  cloudinary:
    cloud-url: ${CLOUDINARY_URL}
  upload:
    dir: ./uploads

resilience4j.ratelimiter:
  instances:
    myApiLimiter:
      limitForPeriod: 40                    # Number of requests allowed in the period
      limitRefreshPeriod: 1s                # The time period
      timeoutDuration: 0                    # How long to wait for permission (0 = fail fast)

  

  